cc_library(
    name = "Assumption",
    hdrs = ["Assumption.hh"],
)

cc_library(
    name = "Background",
    hdrs = ["Background.hh"],
)

cc_library(
    name = "Character",
    srcs = ["Character.cc"],
    hdrs = ["Character.hh"],
)

cc_library(
    name = "GameAction",
    hdrs = ["GameAction.hh"],
)

cc_library(
    name = "GameObject",
    srcs = ["GameObject.cc"],
    hdrs = ["GameObject.hh"],
)

cc_library(
    name = "InputHandler",
    srcs = ["InputHandler.cc"],
    hdrs = ["InputHandler.hh"],
)

cc_library(
    name = "Platform",
    srcs = ["Platform.cc"],
    hdrs = ["Platform.hh"],
)

cc_library(
    name = "Renderer",
    srcs = ["Renderer.cc"],
    hdrs = ["Renderer.hh"],
)

cc_library(
    name = "Screen",
    srcs = ["Screen.cc"],
    hdrs = ["Screen.hh"],
)

cc_library(
    name = "Texture",
    srcs = ["Texture.cc"],
    hdrs = ["Texture.hh"],
)

cc_library(
    name = "Time",
    srcs = ["Time.cc"],
    hdrs = ["Time.hh"],
)

cc_library(
    name = "Types",
    hdrs = ["Types.hh"],
)

cc_library(
    name = "World",
    srcs = ["World.cc"],
    hdrs = ["World.hh"],
)

cc_library(
    name = "Zone",
    srcs = ["Zone.cc"],
    hdrs = ["Zone.hh"],
)
