cc_library(
    name = "Direction",
    srcs = ["Direction.cc"],
    hdrs = ["Direction.hh"],
)
cc_library(
    name = "Line",
    srcs = ["Line.cc"],
    hdrs = ["Line.hh"],
)
cc_library(
    name = "MathHelpers",
    srcs = ["MathHelpers.cc"],
    hdrs = ["MathHelpers.hh"],
)
cc_library(
    name = "Real",
    srcs = ["Real.cc"],
    hdrs = ["Real.hh"],
)
cc_library(
    name = "Rectangle",
    srcs = ["Rectangle.cc"],
    hdrs = ["Rectangle.hh"],
)
cc_library(
    name = "Vect2D",
    srcs = ["Vect2D.cc"],
    hdrs = ["Vect2D.hh"],
)
