cc_library(
    name = "Component",
    srcs = ["Component.cc"],
    hdrs = ["Component.hh"],
)
cc_library(
    name = "Entity",
    srcs = ["Entity.cc"],
    hdrs = ["Entity.hh"],
)
cc_library(
    name = "EntityManager",
    srcs = ["EntityManager.cc"],
    hdrs = ["EntityManager.hh"],
)
cc_library(
    name = "Identity",
    srcs = ["Identity.cc"],
    hdrs = ["Identity.hh"],
)
