cc_library(
    name = "Logging",
    srcs = ["Logging.cc"],
    hdrs = ["Logging.hh"],
)
cc_library(
    name = "LoggingDemo",
    srcs = ["LoggingDemo.cc"],
    hdrs = ["LoggingDemo.hh"],
)
cc_library(
    name = "Overrides",
    srcs = ["Overrides.cc"],
    hdrs = ["Overrides.hh"],
)
cc_library(
    name = "Settings",
    srcs = ["Settings.cc"],
    hdrs = ["Settings.hh"],
)
cc_library(
    name = "Utils",
    srcs = ["Utils.cc"],
    hdrs = ["Utils.hh"],
)
