cc_library(
    name = "DrawingComponent",
    srcs = ["DrawingComponent.cc"],
    hdrs = ["DrawingComponent.hh"],
)
cc_library(
    name = "PositionComponent",
    srcs = ["PositionComponent.cc"],
    hdrs = ["PositionComponent.hh"],
)
