cc_library(
    name = "Duplication",
    srcs = ["Duplication.cc"],
    hdrs = ["Duplication.hh"],
)
cc_library(
    name = "WADLoader",
    srcs = ["WADLoader.cc"],
    hdrs = ["WADLoader.hh"],
)
cc_library(
    name = "ComponentLoaders",
    srcs = ["ComponentLoaders.cc"],
    hdrs = ["ComponentLoaders.hh"],
)
cc_library(
    name = "Duplication",
    srcs = ["Duplication.cc"],
    hdrs = ["Duplication.hh"],
)
cc_library(
    name = "EngineLoaders",
    srcs = ["EngineLoaders.cc"],
    hdrs = ["EngineLoaders.hh"],
)
cc_library(
    name = "EntityLoaders",
    srcs = ["EntityLoaders.cc"],
    hdrs = ["EntityLoaders.hh"],
)
cc_library(
    name = "WADLoader",
    srcs = ["WADLoader.cc"],
    hdrs = ["WADLoader.hh"],
)
