cc_library(
    name = "ComponentLoaders",
    srcs = ["ComponentLoaders.cc"],
)

cc_library(
    name = "Duplication",
    srcs = ["Duplication.cc"],
    hdrs = ["Duplication.hh"],
)

cc_library(
    name = "EngineLoaders",
    srcs = ["EngineLoaders.cc"],
)

cc_library(
    name = "EntityLoaders",
    srcs = ["EntityLoaders.cc"],
)

cc_library(
    name = "WADLoader",
    srcs = ["WADLoader.cc"],
    hdrs = ["WADLoader.hh"],
)
