#pragma once
#include "Types.hh"

// EntityID is a unique identifier for an Identity, determined
// by IdentityManager; it cannot be modified or generated by users
// of the Identity.
typedef string EntityID;

// EntityName is a string-like object that users of Identity can construct
// from strings, and allows them to name Identities.
typedef string EntityName;
