cc_library(
    name = "BoundingBox",
    srcs = ["BoundingBox.cc"],
    hdrs = ["BoundingBox.hh"],
)
cc_library(
    name = "CharacterPhysicsComponent",
    srcs = ["CharacterPhysicsComponent.cc"],
    hdrs = ["CharacterPhysicsComponent.hh"],
)
cc_library(
    name = "Collision",
    srcs = ["Collision.cc"],
    hdrs = ["Collision.hh"],
)
cc_library(
    name = "CollisionComponent",
    srcs = ["CollisionComponent.cc"],
    hdrs = ["CollisionComponent.hh"],
)
cc_library(
    name = "PhysicsComponent",
    srcs = ["PhysicsComponent.cc"],
    hdrs = ["PhysicsComponent.hh"],
)
cc_library(
    name = "PhysicsHelpers",
    srcs = ["PhysicsHelpers.cc"],
    hdrs = ["PhysicsHelpers.hh"],
)
cc_library(
    name = "PhysicsManager",
    srcs = ["PhysicsManager.cc"],
    hdrs = ["PhysicsManager.hh"],
)
